language: python

python:
  - "3.4"

sudo: false

before_install:
  - pip install -r "requirements.txt"
  - pip install httpretty==0.8.6
  - pip install flake8
  - pip install coveralls

install:
  - ./setup.py install

script:
  - flake8 .
  - cd tests
  - coverage run --source=perceval --omit="*.egg*" run_tests.py

after_success:
  - coveralls
